Enhance EKS deployment workflow and IAM configurations
- Added debug step to check EKS access entry during deployment.
- Updated kubeconfig command for EKS.
- Modified IAM role policies to include SSM permissions.
- Changed EKS authentication mode to API only.
- Added environment and management tags to IAM roles.
- Improved route table association resource names for clarity.
- Corrected description for private subnets variable.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -52,14 +52,17 @@ jobs:
         with:
             image-ref: ${{ steps.login-ecr.outputs.registry }}/secure-app:${{ github.sha }}-${{ github.run_number }}
       
-      - name: Wait for EKS access to propagate
-        run: |
-          echo "Sleeping for 60 seconds to allow EKS IAM access policy to propagate..."
-          sleep 60
       - name: Update kubeconfig
         run: |
           aws eks --region us-east-1 update-kubeconfig --name secure_cluster
-
+      - name: Debug EKS Access Entry
+        run: |
+          echo "Checking if GitHub Actions access entry exists..."
+          aws eks get-access-entry \
+            --cluster-name secure_cluster \
+            --principal-arn arn:aws:iam::831274730062:role/github-actions-role \
+            --region us-east-1 || echo "Access entry not found or not ready."
+            
       - name: Wait until GitHub Actions role access is ACTIVE
         run: |
           echo "Waiting for GitHub Actions IAM access entry to become ACTIVE..."
@@ -103,7 +106,7 @@ jobs:
       
       - name: Deploy to EKS 
         run: |
-          helm upgrade --install secure-app ./myapp-helm-chart --namespace default 
+          helm upgrade --install secure-app ./myapp-helm-chart --namespace default --create-namespace
 
       - name: Verify deployment
         run: |
